pull_request_rules:
  - name: Auto-approve test.txt
    conditions:
      - author=cgundy
      - files=test.txt
      - "#files=1"
    actions:
      review:
        type: APPROVE
        message: Auto-approving changes to mainnet-canister-revisions.json
      label:
        add:
          - automerge-squash
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - files=test.txt
      - base=main
      - label=automerge-squash
    actions:
      queue:
