name: CI Main

on:
  workflow_call:
    inputs:
      commit-sha:
        description: The commit sha to run the CI on
        required: true
        type: string

jobs:
  test-workflow-secret:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Test Workflow Secret
        run: |
          echo "Test Workflow 1"
          echo "Running on commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"

  test-workflow-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Test Workflow 2
        run: |
          echo "Test Workflow 2"
          echo "Running on commit: $(git rev-parse HEAD)"

  test-workflow-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Test Workflow 3
        run: |
          echo "Test Workflow 3" 
          echo "Running on commit: $(git rev-parse HEAD)"