name: Kickoff Manual

on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'The commit SHA to run the workflow on'
        required: true
        default: ''

jobs:
  ci-main:
    name: CI Main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/ci_main.yml
    secrets: inherit
    with:
      commit-sha: ${{ inputs.commit-sha }}

  post-commit-status:
    name: Post Commit Status
    runs-on: ubuntu-latest
    needs: [ci-main]
    if: success() || failure()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - uses: actions/github-script@v7
        with:
          script: |
            let state, description;
            
            if ('${{ needs.ci-main.result }}' === 'success') {
              state = 'success';
              description = 'Required checks passed';
            } else if ('${{ needs.ci-main.result }}' === 'failure') {
              state = 'failure';
              description = 'Required checks failed';
            } else {
              state = 'error';
              description = 'Required checks completed with unexpected result';
              console.log(`Debug: ci-main result was '${{ needs.ci-main.result }}' for event: ${{ github.event_name }}`);
            }

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ inputs.commit-sha }}',
              state: state,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: description,
              context: 'ci-required-checks'
            });
            
            console.log(`Set commit status: ${state} - ${description}`);
