name: Kickoff Manual

on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'The commit SHA to run the workflow on'
        required: true
        default: ''

jobs:
  validate-commit:
    name: Validate Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate commit SHA exists
        run: |
          git fetch origin ${{ inputs.commit-sha }} --depth=1

  ci-main:
    name: CI Main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/ci_main.yml
    secrets: inherit
    with:
      commit-sha: ${{ inputs.commit-sha }}
