name: Kickoff Manual

on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'The commit SHA to run the workflow on'
        required: true
        default: ''

jobs:
  ci-main:
    name: CI Main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/ci_main.yml
    secrets: inherit
    with:
      commit-sha: ${{ inputs.commit-sha }}

  post-commit-status:
    name: Post Commit Status
    runs-on: ubuntu-latest
    needs: [ci-main]
    if: success() || failure()
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - uses: ./.github/actions/post-commit-status
        with:
          commit-sha: ${{ inputs.commit-sha }}
          run-result: ${{ needs.ci-main.result }}
