name: Test External Workflow

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-main:
    name: CI Main
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    steps:
      - name: Run CI Main
        run: |
          echo "Running CI Main"

  required-checks:
    name: Required Checks
    runs-on: ubuntu-latest
    needs: [ci-main]
    if: always()
    steps:
      - name: Run required checks
        run: |
          echo "Running required checks..."
