name: WF Kickoff

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-main:
    name: CI Main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/ci_main.yml
    secrets: inherit
    with:
      commit-sha: ${{ github.sha }}

  # required-checks:
  #   name: Required Checks
  #   runs-on: ubuntu-latest
  #   needs: [ci-main]
  #   if: always()
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     COMMIT_SHA: ${{ github.event.pull_request.head.sha }} # only needed for PR, so can be empty otherwise
  #     REPO: ${{ github.repository }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run required checks
  #       shell: bash
  #       run: |
  #         set -euo pipefail
          
  #         if [[ "${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}" == "true" ]]; then
  #           if [[ "${{ needs.ci-main.result }}" == "success" ]]; then
  #             echo "✅ Required checks passed"
  #           elif [[ "${{ needs.ci-main.result }}" == "failure" ]]; then
  #             echo "❌ Required checks failed"
  #             exit 1
  #           elif [[ "${{ needs.ci-main.result }}" == "skipped" ]]; then
  #             echo "⏭️ Required checks were skipped"
  #             exit 1
  #           fi
  #         elif [[ "${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}" == "true" ]]; then
  #           ./ci/scripts/check_manual_run.sh
  #         else
  #           echo "No required checks to run for event: ${{ github.event_name }}"
  #         fi


  post-commit-status:
    name: Post Commit Status
    runs-on: ubuntu-latest
    needs: [ci-main]
    if: success() || failure()
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Test Workflow 3
        uses: actions/github-script@v7
        with:
          script: |
            let state, description;
            
            if ('${{ needs.ci-main.result }}' === 'success') {
              state = 'success';
              description = 'Required checks passed';
            } else if ('${{ needs.ci-main.result }}' === 'failure') {
              state = 'failure';
              description = 'Required checks failed';
            } else {
              state = 'error';
              description = 'Required checks completed with unexpected result';
              console.log(`Debug: ci-main result was '${{ needs.ci-main.result }}' for event: ${{ github.event_name }}`);
            }

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.pull_request.head.sha }}',
              state: state,
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: description,
              context: 'ci-required-checks'
            });
            
            console.log(`Set commit status: ${state} - ${description}`);
