name: WF Kickoff

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-main:
    name: CI Main
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/ci_main.yml
    secrets: inherit
    with:
      commit-sha: ${{ github.sha }}

  post-commit-status:
    name: Post Commit Status
    runs-on: ubuntu-latest
    needs: [ci-main]
    if: success() || failure()
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/post-commit-status
        with:
          commit-sha: ${{ github.sha }}
          run-result: ${{ needs.ci-main.result }}
